global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'moodle'
    metrics_path: '/local/prometheus/metrics.php'
    params:
      token: ['YTFmOTMyZDU1NzU0YzEzNWMzZTIyYmNhZjc0NzAzZjI=']
    static_configs:
      - targets: ['moodle:8080']