apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: OtherDataSource  # Example of a second data source
    type: mysql
    access: proxy
    url: http://some-other-database:3306
    isDefault: false  # Ensure this is set to false
    editable: true